### ISSUE TITLE
Sprint #2 Retrospective Review

### ISSUE THREAD

**Issue by qspraut** [dartmouth-cs98/21f-macro-meals#102]
* Retrospective on Sprint #2: 
    * members in attendance:
        ![selfie proof of meeting](https://imgur.com/DoxSG8c.png)
        - [x] Alex
        - [x] Anand
        - [x] Brandon
        - [x] Quinn
    * what worked well
        * Found and integrated a food classification and calorie estimation repo
        * Began training model on whole food images 
        * Fixed bugs in front-end-S3 and API-database communications 
        * Replaced hard-coded test values with live DB data in frontend
        * Prepped frontend for UI development
        * Implemented state management and navigation
    * what didn't
        * Ran into bugs when trying to save trained model; will need to fine-tune next week and start on test images 
    * self assessment on progress
        * We made a great amount of progress this week. We finished connections and populated frontend components with live data, prepped the frontend for UI development, and have a working ML model for food / volume identification
        * Estimate of progress towards MVP: 50% 
        * lay out *each* of the following weeks till end of term with brief goals for each
          * current week: goals
              * Create nav pages for all screens
              * Implement full UI of all core components
              * Get ML classification live on Flask server
              * Get classification working for preexisting image URLs (not live from camera)
          * week 9: goals
              * Store pictures taken by camera
              * Classify new images instead of static URLs
              * Implement user authentication 
          * week 10: goals
              * User testing
              * Adding lower priority features such as user community

**Comment by timofei7** [comment]
love "great amount of progress"!  plan sounds good for a demo at the end of term of the core functionality.  don't forget to include screenshots of things (was missing from my markdown, my bad).
