### ISSUE TITLE
T2 Project Reflection and Next Steps Worksheet

### ISSUE THREAD

**Issue by qspraut** [dartmouth-cs98/21f-macro-meals#159]
## Original idea
*Revisit your original goals (check out your project proposal).*

* Create an application for users to quickly and easily determine the calorie and macronutrient content of a food
* Allow users to track their calorie and macronutrient intake over a given time period

#### MVP Progress?
*What progress did you make towards your original MVP / on your stretch goals?*

* Completed most of the UI component
* Established basic user flow: sign-in, meal logging, history, etc. 
* Constructed very basic classifier; able to classify fruits and estimate macros with low to moderate accuracy

#### How is it different?
*How is your project different from what you envisioned?*
* Unique UI that displays macronutrient information in intuitive way
* Low accuracy calorie identification
* Easy volume identification with fingertip vs harder methods
* Identification with only a few simple foods

#### Still happy with direction?
*Most importantly, are you still happy with the direction that your project is headed?*

* Yes 
* We still have to tackle the most difficult part (accurate macro estimation using image processing), but it's good to have a clear and definite goal 

#### What do you wish went differently?
*What do you wish had gone differently / are there features you wish you hadn't made or made differently?*
* We should have researched classification and volume estimate models more closely and constructed a more accurate/tailored one
* We should tailor the image capture/save to work on iOS devices
* We should train the model on more foods and improve classification for current foods
* More robust testing on the UI and better understood existing UI language of diet tracking apps

## Feedback
*What feedback from last term do you think is relevant and interesting to incorporate. List your feedback broadly and label them with how they stack up for your vision. These may already be in ZenHub but after this discussion they should be.*

* [critical 🔥]
    * Classification is pretty poor - need to alter model we are using
    * Get it on a phone!!!!!!!
    * Allow users more control over their history
    * Alter interface for easier userflow
    * Implement goal tracking
    * Stylistic updates
* [stretch goal 🍦]
    * Implement social aspect (food / meal sharing)
    * Learn from images taken by users
* [rejected ⛔]
    * N/A - we agreed with all of the feedback and plan on addressing each item

#### Questions
*Think about where the project is headed. What are some questions that you/users/me have about direction/features/functionality that could use some validation?*

* Some users were confused about the purpose of the mood meter; how can we make it (and our more general concern about eating disorders) more clear? 
* Would users find it helpful to recommend common recipes based on frequently eaten foods? 
* Would users be willing to do something like carry around a qr code "coin" that would help with image processing (by providing a standard measure of size)? Or should we continue using fingers/plates/etc.?  

#### Answers
*Think of ways that you might validate these: discussion with your team, advice from me, polling the class, asking users, and/or collecting and analyzing usage data. Write down some ideas here. This isn't how to validate your project as a whole, but about specific feedback/features.*
* For classification, talk to TA with knowledge of image classification and computer vision to help improve model
* Test product with more users to develop more intuitive UI
* Gather more beta testers and develop more comprehensive understanding of existing UI language.
* Do use/class polls to strike the right balance between convenience and classification accuracy 

## Vision
*Refine your vision.*
* Our vision is to create an app that *works*. Currently our classification is incredibly poor which detracts from the cool-ness of our progress dramatically. Implementing more robust classification and an improved UI/UX are our top priorities.

#### Feedback Analysis
*How does the current feedback/user testing/progress change how you think about the direction of the project?*
* It mostly told us what we already suspected - that we have a lot of work to do! Most of the feedback started with "This is so cool, but..." which tells us that we are on the right track. Fixing the classification issues and improving the user experience and flow would go a long way towards making our app launchable!

#### Pivot/Adjustment
*If you were to consider a pivot or adjustment in what the product is, what would it be?*
* Implement a social element which allows users to share and find new foods/meals
* A meal recommendation platform based on the user's fitness/dietary goals
* A restaurant finder that uses the user's previously eaten foods to filter out various cuisines the user might like

#### Ideal Goal
*In an ideal world if you could build out your project to be anything without any constraints of time or skill what would you want to do? Dream big — you can do more than you think. Try to push the limits. This does **not** commit you to anything, so don't worry about overpromising, this is to get you dream about where you **really** want your project to go without constraints. Please don't skimp on this part.*
* Digital fingerprint of a given person's diet and tastes
* Classify and estimate food calorie/macro content with >90% accurracy
* Create a UI/UX that is clear and accommodates as much requested functionality as possible
* Create a social platform for people to share their food and diet goals with others

#### Mission Statement
*Now write a mission statement for your project as you see it after all of this great brain activity. Just a few sentences suffices.*
Our mission is to make achieving diet related goals more accessible by simplying the food tracking and meal planning process. We also hope to support individuals in their journey by creating a community of people with similar goals.

## How to get there
*Now that you've thought about where your project is headed and where you want it to go write down how you might approach getting there.*
* Identify/develop new classification/volume estimation models
* Work on fitness community feature to facilitate connections
* Create intuitive and informative UI by getting feedback from users and implementing new ideas

#### What are your concrete next steps?
* Gather as much training data as possible 
* Revise classification model to make macro estimation more accurate; work with TA to make sure we're working in the right direction 
* Streamline the UI/UX, get more feedback from Tim and the TA's 

#### What are some blockers in your way? 
* Image processing is hard to refine, both in itself and because we aren't super experienced in it as a team 

## TeamWork
*lastly, at the end of last term in the term summary you did a bit of work around teamwork. this is just a reminder for everyone to revisit that and if you have any new or further thoughts after the break feel free to record them here.*
* Most important point from that summary - more communication over Slack & task updates over ZenHub as needed

**Comment by romano-w** [comment]
(👍) Planning looks good!
