### ISSUE TITLE
Personal Success - Anand

### ISSUE THREAD

**Issue by Mittanand** [dartmouth-cs98/21f-macro-meals#160]
# Anand | Personal Goals
*what does success for this class mean to you?*
* I gain a deeper understanding of how to turn an idea into a fully functional, ready to ship product
* I have a cool project to add to my portfolio
* I gain a better understanding of how to create classification models

## Challenges
*what are some challenges you foresee?*
* Learning new ML techniques to help with construction new models
* Learning frontend development techniques and how to connect different parts of the project

**Comment by timofei7** [comment]
great goals and challenges, on your way to success.
