### ISSUE TITLE
Alex Wong | Personal Goals

### ISSUE THREAD

**Issue by alexdavidwong** [dartmouth-cs98/21f-macro-meals#163]

**Comment by alexdavidwong** [comment]
# Alex Wong | Personal Goals
*what does success for this class mean to you?*

* I learn how to build an app from the ground up
* Building confidence in my coding abilities
* Macro is usable in my daily life

## Challenges
*what are some challenges you foresee?*

* I think burnout might be a real problem 
* For myself is getting too stuck with some styling adjustments and spending a disproportionate amount of time on them as compared to its impact on the project
* As I drill deeper into styling in expo may come across some difficult styling packages that interfere with the rest of the project

**Comment by timofei7** [comment]
great goals! 

definitely happens that details end up overshadowing the whole - try to keep the big picture features in mind and reprioritize often with the team to make sure you are all aligned in goals and roadmap.
