### ISSUE TITLE
Brandon Feng | Personal Goals 

### ISSUE THREAD

**Issue by brandonfeng** [dartmouth-cs98/21f-macro-meals#164]
## Success 
*what does success for this class mean to you?*

My primary responsibility is building out the food classification and macro estimation models. So for me, building a model that actually works to some degree would be a success, and a major one at that. To build a model that would be able to classify and measure foods (relatively) correctly, across a broad range of food items (ranging from fruits to meats to "compound" dishes like sandwiches and soups) would be amazing just in terms of having the knowledge that we tackled such a difficult project. Also, I am passionate about personal fitness, so having the product work well enough to be released out into the wild so that it could help others would be a real plus. 

## Challenges
*what are some challenges you foresee?*

I, along with the rest of our team, have limited experience in image processing, AI, etc. Building up a model good enough to be better than guesswork will be very difficult; unless we want to Frankenstein together a bunch of open-source projects, we'll have to consult people outside the team to build our algorithms, as well as do a good amount of homework ourselves.

A more personal challenge is simply staying motivated. With my senior year coming to a close (I'm graduating a term early), it gets harder and harder to focus on school. I love this project and my team, and hopefully that's enough to sustain me through a bit of a senior year slump.

**Comment by timofei7** [comment]
great comments.  last term — i'm sure that comes with a lot of emotions!  i think frankensteining is definitely an option as is combining the model with public image recognition apis.
