### ISSUE TITLE
Photo uploading doesn't work on iOS

### ISSUE THREAD

**Issue by qspraut** [dartmouth-cs98/21f-macro-meals#165]

**Comment by timofei7** [comment]
@qspraut  one other option if this is still giving you trouble is to use the aws javascript sdk directly from the the react-native app - you have to be more careful with your aws keys (ie never making your code public or using config files not added to git) but would save the step of getting the signedUrl.  although that doesn't seem to be the problematic part.   for instance here is an expo example that does that: https://github.com/expo/examples/blob/master/with-aws-storage-upload/App.js.

**Comment by qspraut** [comment]
Thanks for the pointer, Tim! I'm beginning to think that the issue may just be within the expo-camera. I think my next approach is to shift our app over to using a different image-taking package, such as the imagepicker used in that demo. I appreciate the help!
