### ISSUE TITLE
Final Success Metrics and Validation Plan

### ISSUE THREAD

**Issue by qspraut** [dartmouth-cs98/21f-macro-meals#201]
# Success Metrics and Validation Plan

## Team Goals
*Discuss and identify any team goals that you think would be important to tackle*

* finish implementing food recomendation feature
* sharpening the ML algorithm to:
    * calculate macros more accurately
    * classify food more accurately
* flesh out approach to journal food
* (stretch) implement a social component to the app

## Success Metrics
*what are some success metrics that you might use for your product / customers / your team / your cs98?*

* get many claps on our product from a published Medium post
* food is correctly tagged and calculated with high accuraccy (~75%+)
* achieve at least 1/2 of our stretch goals
* demo our product 2+ times in weeks prior to technigala
* have an app that is usable by ourselves and others

## Validation Plan
*how do you get from goals to success metrics that are validated? this can be user testing, performance metrics, a public demo, etc. this is your implementation plan to gather the above.*

* ask variety of students to beta test in preparation for larger public tests
* consistently meet in person to continue progress on our app
* publish and market our Medium post write up about our approach to tagging food items
* implement most of the stretch features to create a community within the app

**Comment by timofei7** [comment]
this looks great!  what were the other stretch features you are interested in? and happy to give any feedback on the flows you are thinking of.
