### ISSUE TITLE
Sprint Retrospective #8

### ISSUE THREAD

**Issue by qspraut** [dartmouth-cs98/21f-macro-meals#284]
## Sprint #8 Retrospective:
* members in attendance:
    ![selfie proof of meeting](https://imgur.com/dbjNfSf.jpg)
  - [x] Alex
  - [x] Anand
  - [x] Brandon
  - [x] Quinn
* what worked well
  * Launched app via Testflight
  * Distributed app to external user testers
  * Minimized classification failed errors by fixing null volumes and minimizing required number of contours
  * Updated patch to spoonacular, sped up performance and solved styling problems ![newStyle](https://i.imgur.com/H8gOrb4.png)
  
* what didn't
  * displaying the menu item on a new page, issues with passig a element between pages
  * Still having issues with some improper classification, but high accuracy with the confidence scores and multiple recommendations
  
* self assessment on progress
  * where are you in relation to progress towards product and milestones?
    * Our app is 100% complete. We are adding some last minute polishes to create a seamless UI experience, maximize model accuracy, and further flesh out some stretch features.
    * lay out *each* of the following weeks till end of term with brief goals for each
      * Current week: Make final adjustments and test with more users, write Medium article

* briefly summarize any other topics/discussions
    * We feel very happy with our status at Week 9
    * We plan to finalize the app and work on the medium article / publicity for the rest of the term

**Comment by timofei7** [comment]
nice!  please invite tim@zingweb.com to your internal testing users!  thanks!
